# Generated by Django 3.2.9 on 2022-02-26 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('-created',)},
        ),
    ]
