# Generated by Django 3.2.9 on 2022-03-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
    ]
