# Generated by Django 3.2.9 on 2022-03-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20220318_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='lng',
            new_name='longitude',
        ),
    ]
